### ISSUE TITLE
My notifications are very tiny!

### ISSUE THREAD

**Issue by eduardoalcantara** [tim-kuteev/ngx-toast-notifications#1]
I did everything that was told in the 'simple usage' section, but my notifications are shown very, very small, like 200x33px. Any idea why this is happening and how to correct it?

I am using FUSE template: http://angular-material.fusetheme.com

**Comment by tim-kuteev** [comment]
Hi @eduardoalcantara,

All the sizes are relative to the root html element. You can specify bigger font size for the root element:

```css
html {
  font-size: 18px;
}
```
That will make notifications bigger.

Let me know if you happy with that.
