### ISSUE TITLE
Ability to prevent duplicate toasts

### ISSUE THREAD

**Issue by xyassini** [tim-kuteev/ngx-toast-notifications#2]
Should be a very handy feature as sometimes, it happens that people get the same notification multiple times because they're perhaps pressing the save button multiple times.

I think comparing caption & text of present toasts should be enough for this feature.

**Comment by tim-kuteev** [comment]
Hi @xyassini,

Good idea, I will consider this feature for the next release. Thanks for the feedback.

**Comment by fairmutex** [comment]
If you have something specific for this use case it would help explaining the problem in detail. As for me
people shouldn't be allowed to press save button twice unless it is intended. Block the save button on first click. and enable it if it fails to save. And if it is intended to have multiple saves, notifications should happen every time as from UX  it will leave the user thinking the second save didn't occur and will keep clicking the save button.
