### ISSUE TITLE
is there any option to place toaster notification at my desired position i.e top right instead of default position i.e bottom-right?

### ISSUE THREAD

**Issue by fahadsubzwari924** [tim-kuteev/ngx-toast-notifications#3]
I have implemented `ngx-toast-notifications` in my `angular8` project. But issue is that default toaster notification is appearing on bottom-right but i want to make it's position to top-right so is there any option in this module to change the default position?

**Comment by tim-kuteev** [comment]
Hi @fahadsubzwari924,

I'm already working on it, this option will be out next week hopefully. Thanks for the feedback.

**Comment by fahadsubzwari924** [comment]
so how you will update your audience about that new feature? will you update your readme to announce that feature? i just want to know that how will i be notified when your that feature will announce?

**Comment by tim-kuteev** [comment]
@fahadsubzwari924, you (as the participant) will be notified when this issue is resolved. The readme file will be also updated.

**Comment by fahadsubzwari924** [comment]
Thank you for your support. I got the new changes regarding to position.
Should i re-install that package in angular?

**Comment by tim-kuteev** [comment]
@fahadsubzwari924, yes, you should update the package to the latest version to pick up this changes:
`npm install --save ngx-toast-notifications@latest`
then you will be able to set the **position** option to **'top-right'**.

**Comment by fahadsubzwari924** [comment]
@tim-kuteev  Thanks for your great support. Appreciated.
